version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4001:4001"
    volumes:
      - ./src:/app/src
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
